name: Build and Release Themes

on:
  push:
    tags:
      - v*.*.*
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Themes
      run: |
        mkdir -p build
        for dir in */; do
          # Skip unwanted folders
          [ "$dir" = ".github/" ] && continue
          [ "$dir" = "build/" ] && continue
          # Skip files in the root directory
          [ ! -d "$dir" ] && continue

          # Get the theme name from the folder
          theme_name=$(basename "$dir")

          # Check required files exist
          if [[ -f "$dir/theme.json" ]]; then
            find "$dir" -name "*.png" -o -name "*.jpg" | tar -cf "build/${theme_name}.tar" -C "$dir" theme.css theme.json -T -
            echo "Built $theme_name successfully."
          else
            echo "Skipping $theme_name as a required file is missing."
          fi
        done
        
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/*.tar
