name: Build and Release Themes

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Build Themes
      run: |
        mkdir -p build
        for dir in */; do
          # Skip unwanted folders
          [ "$dir" = ".github/" ] && continue
          # Skip files in the root directory
          [ ! -d "$dir" ] && continue

          # Get the theme name from the folder
          theme_name=$(basename "$dir")

          # Check required files exist
          if [[ -f "$dir/theme.css" && -f "$dir/theme.json" ]]; then
            tar -cf "build/${theme_name}.tar" -C "$dir" theme.css theme.json *.png *.jpg *.jpeg
          else
            echo "Skipping $theme_name as required files are missing."
          fi
        done

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: "Themes Release - ${{ github.sha }}"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Tar Files to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/
        asset_name: "*.tar"
        asset_content_type: application/x-tar
